# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnkrView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnkrView

  target 'SnkrViewTests' do
    inherit! :search_paths
    # Pods for testing
    target 'MyApp' do
      install_all_flutter_pods(flutter_application_path)
    end
    
  end

  target 'SnkrViewUITests' do
    # Pods for testing
  end
  target 'MyApp' do
    install_all_flutter_pods(flutter_application_path)
  end
  

end

flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    ## Add these 3 lines to your podfile
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
    
  end
end



